const arregloDeComputadorasAleatorio = [
  { marca: 'apple',
    color: 'rojo',
    ram: 64,
    discoDuro: 1000,
    so: 'windows',
    funciona: true },
  { marca: 'lenovo',
    color: 'rojo',
    ram: 32,
    discoDuro: 2000,
    so: 'windows',
    funciona: false },
  { marca: 'microsoft',
    color: 'gris',
    ram: 64,
    discoDuro: 500,
    so: 'Linux Mint',
    funciona: true },
  { marca: 'dell',
    color: 'blanco',
    ram: 8,
    discoDuro: 500,
    so: 'Linux Mint',
    funciona: false },
  { marca: 'dell',
    color: 'azul',
    ram: 64,
    discoDuro: 2000,
    so: 'macOS',
    funciona: true },
  { marca: 'dell',
    color: 'azul',
    ram: 32,
    discoDuro: 1000,
    so: 'Linux Mint',
    funciona: true },
  { marca: 'dell',
    color: 'rojo',
    ram: 64,
    discoDuro: 1000,
    so: 'Fedora',
    funciona: true },
  { marca: 'hp',
    color: 'azul',
    ram: 8,
    discoDuro: 500,
    so: 'Fedora',
    funciona: false },
  { marca: 'dell',
    color: 'gris',
    ram: 64,
    discoDuro: 4000,
    so: 'windows',
    funciona: true },
  { marca: 'lenovo',
    color: 'gris',
    ram: 32,
    discoDuro: 2000,
    so: 'windows',
    funciona: false },
  { marca: 'lenovo',
    color: 'azul',
    ram: 16,
    discoDuro: 4000,
    so: 'macOS',
    funciona: true },
  { marca: 'apple',
    color: 'gris',
    ram: 64,
    discoDuro: 1000,
    so: 'Fedora',
    funciona: false },
  { marca: 'hp',
    color: 'azul',
    ram: 32,
    discoDuro: 2000,
    so: 'Fedora',
    funciona: true },
  { marca: 'dell',
    color: 'azul',
    ram: 8,
    discoDuro: 4000,
    so: 'Linux Mint',
    funciona: true },
  { marca: 'hp',
    color: 'rojo',
    ram: 8,
    discoDuro: 1000,
    so: 'macOS',
    funciona: true },
  { marca: 'apple',
    color: 'negro',
    ram: 64,
    discoDuro: 2000,
    so: 'Fedora',
    funciona: true },
  { marca: 'lenovo',
    color: 'blanco',
    ram: 8,
    discoDuro: 4000,
    so: 'macOS',
    funciona: false },
  { marca: 'lenovo',
    color: 'negro',
    ram: 32,
    discoDuro: 4000,
    so: 'Ubuntu',
    funciona: true },
  { marca: 'hp',
    color: 'blanco',
    ram: 8,
    discoDuro: 500,
    so: 'macOS',
    funciona: false },
  { marca: 'apple',
    color: 'azul',
    ram: 64,
    discoDuro: 2000,
    so: 'Ubuntu',
    funciona: false
  }
];